language: bash
sudo: required
env:
  global:
    - secure: "RcUhhcHKtvQ54GBLY+GN1j9ufU+59WucghYgVHyZdMlUWROic2SAhxkaOVQdY1j82Qm3cL0EQqAnJl2JtZhNf3x76OmOZeWyLWln2lDki/MR15SQEKg4KyveQSJauITLtdRsCUpjmMPrEnbjAU0f3pmxycoymN7xpPTAzBhXz3VM/h0OKFz6h5tgNEXWA4Cg1Rw2/M8/NQnz6iZb8AzT4acH3ENCrQ3PQr+jSAo/RYdK7HEI41Wxfn4F7XPd+w763pEbmm9tp+UVnkfYBd4DLNOW1vrdail0v8euUU7ynhCc/yHnOhXh1g9A7+Lj1t+1e+OXT43SnH4AME4tBAmDipTjqEJrA/rMyKmxRJzpupJcwwUkgKw6Tz4g0Zfmg/335aADCSd5ae9CJ03jbyIZbLDjer/EFKyP45mRfq/+/L4GLNOhpWXLqWNRWwwEp2QH3PcenjCxw/DhhZluWkygRKfGMLmM97gncye5wwxwkN9/bb0tG2htcCYHfX28Dqc+CPil8C5U9FssUGa8rozCMt4o/7XFEKPIv8C9gSg2kRq6YcZ2VHy7Tep/KqyU2mv+0twGkSBYDN0/a0zxnAGNwfYHHxkIOKepxCVqu7NFZyMGjLmV6VI5iCaSBuoMzU5B8E/7jWHsi6SpDdEfBs/LlEywmT54WmdcULP6KK2w05s="
    - secure: "s6VU8+FzGlBHsQ5cRk9XpU+LOpeX6Yn0nlpZrUwD/+F7aXOO9CjI1W9MTP7PMnBQXOTaL+agG1eTCy0oO40tOPdLtH4eEw1ixCN4VsS0xSQPgynsRb9XKdWs42xyHJuJCeY37Gydxhuyl7trHDiYYUSUxlOkostFlWaXDbe5FJSIVxhSGyKMioz/Kk5ek/TZFF2saW3G3b22UENSBgLxID36XGcTqYfX1eR3W+YQskVL8FRwLtT5CKAO9fr6BkVf5fA/ZtW7T3+b0nPp2DmQPwCq67g9WznyxEBCzZqjI0SbrPjxVe+wzuBb6eDtRpcioMUM6X6ixzm4+l4WCvDkTJ2lSfU4i3gaUsKdB/gHl625LTvCC87+WSUg3e1cgT58xY6TQQm05+Wa/dAyxAmXnc28zFJz3VUtnB7H6CfTOrFSYeVwG26WMUvu/vDdwmoHIsVfZAvoCY9bQFAtHQ/dLrSXanf0tqY4izfe8iIGEOWKWhsGvOhopGkiQQqAbaMbYqIQgKSehTdYTOT6vs4mCc4vsK882+++mdh2MXoscYWfdDRSf8ETI+TolSCAwZjnttcTwIgIwpTh0RGEATDjiqyesADVwXea6ziX242d1VvxGdolDVR3MQKQA5e/qw4fXOwbTzb0y+goSojblLM/bEFlfPgRbTMVfjoXdXwHUPM="
    - secure: "xWpNB7hqxXFSTruE34rALGXaV5/PLhW0uZmQzr+nb8KdxBOI42/A+uEb0KVV0RRu+UDADZLEcIpMK1BesAVkAlU5SqPG0ZTZmygrg5h1adrhqNrIghPW/v2g9vmkILnBA6EC+rNF974MMf0eAqAcgguJXHGdfBD3hto34MYyT+G2GAP0CF27pq87v0jKigjAUahytpQnXY4lPNTd0EzqZro6nhd77ALkWCcCAjsgGNEVPpEMdsORsxvul4xUnLKtwS2LOoMjdH/aKQa5m1WngiIy463CzOeYC+yaVkO20QDY9BzFJEQXiZjeTxCERjODtEKt9QNbLlOszwskd2/hyujEgOyJq34DSVb1IChXknHBsQ9J8yG3Rmbti+P4kRyTcOaiIFMZ6p9ypPcAPUX82oEjPrvUXo7dFiT0s+gbXtSNFtFZGZLetNIG9cwcJfIDIj1ht/fePKkJOKMT9E9B+GefPeT6VPIlHgMpwnqiNLCUXL7iD9l3CYks0rOw91767xvW+fLkAWxPGmgs5r1TzZuwPIDAk0TXy8PnfI6BP7CSwuAA4cLjHYDP7kM2/v4Aeec2ePM3VpJQCTct+EaU/sIVdUq9Sq19k9lr4BcLfcosc/Km+yXQSNW2kBPdnzJFGRYnI0K8GuG+FVuYm1HMAjfX2gGYF0/33FxGLGEjGD8="
    - K8S_OPS_REPO_BRANCH=master
    - K8S_OPS_REPO_SLUG=OriHoch/knesset-data-k8s
    - DOCKER_IMAGE=orihoch/knesset-data-pipelines
    - DEPLOY_YAML_UPDATE_FILE=environments/production-kamatera/values.auto-updated.yaml
    - DEPLOY_VALUES_CHART_NAME=pipelines
    - DEPLOY_VALUES_IMAGE_PROP=image
    - DEPLOY_COMMIT_MESSAGE="automatic update of knesset-data-pipelines"
    - DEPLOY_GIT_EMAIL=knesset-data-deployer@null.void
    - DEPLOY_GIT_USER=knesset-data-deployer
services:
  - docker
script:
  - curl -s https://raw.githubusercontent.com/hasadna/hasadna-k8s/master/apps_travis_script.sh > .travis.sh
  - |
    export FORCE_RECREATE=`echo $TRAVIS_COMMIT_MESSAGE | grep -q -- --force-recreate && echo ' --force-recreate'`;
    export DEPLOY_COMMIT_MESSAGE="${DEPLOY_COMMIT_MESSAGE}${FORCE_RECREATE}";
    bash .travis.sh script
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis-deploy.sh
  on:
    branch: master
    condition: |
      `echo "${TRAVIS_COMMIT_MESSAGE}" | grep -q -- --no-deploy && echo 1` != "1"
